server {
    listen 80;
    server_name devop-midterm2026.online www.devop-midterm2026.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 302 http://localhost:3000$request_uri;
    }
}
